### ISSUE TITLE
can't follow it

### ISSUE THREAD

**Issue by mpstaton** [petipois/astro-appwrite-starter#1]
I'm on your YouTube channel.  I can't follow your up and running.

I am desperately trying to connect Astro 5 to Appwrite.  

Right now, I seem to be missing where to find the environment variables in Appwrite and how to store them in the Astro project.  

However, I have done several tutorials on Astro and I have never seen a middleware.js file.  And I've also never seen all the code you have in the env.d.ts file.  

FYI I have learned to code several times. Not an idiot.  

Please, please please make your videos easy to follow along to.  Like, assume your grandma will need to follow along.

**Comment by petipois** [comment]
thanks for the feedback
 i need to update to astro 5

**Comment by mpstaton** [comment]
@petipois I love the direction of the content.  I'm really trying to adapt (as a founder, investor, consultant, not as a full-time developer) to this whole new world of front ends and backends that do a lot of magic.  It feels so close I can taste it that I can prototype something without really needing to go to engineering, or to raise money to start a company.  Like, I can just connect AppWrite to Astro and Boom!  But, I've been poking around for a few days per month and there has not been a Boom! moment.  Anyway, thanks for all your content.  You're great, I just struggle ;)
